### ISSUE TITLE
Invisible / Invulnerable ships

### ISSUE THREAD

**Issue by Crendraven** [czartrak/Czartraks-Ship-Pack#6]
Steam version 0.9.10
Windows 7 64 bit
Other mods:
Becca's Endless Expansion
Amalgamation
Adde

In the "Battle for Rastaban" mission, there are two invisible invulnerable ships that cannot be disabled and thus mission cannot be completed. They have 5 electron turrets fitted.

I've narrowed it down to this plugin specifically, as disabling it stops them spawning. I tried removing the suspected ships from the fleet list (suspected navy destroyer) but it repopulates when the game is loaded.

**Comment by Yastiandrie** [comment]
Its the Navy Battlecruiser (Mark II) in the variants file
Change
	sprite ship/battlecruiser
To
	sprite ship/battlecruiserncsp

Has fixed it for me as a temp measure

**Comment by czartrak** [comment]
Multiple years later, this problem should be solved
